export interface ExampleSequence {
  name: string;
  description: string;
  hasMockReport: boolean;
  sequence: string;
}

export const exampleSequences: ExampleSequence[] = [
  {
    name: "ORD-2024-0847",
    description: "Protein sequence, 398 aa — 4 domains detected",
    hasMockReport: true,
    sequence: `>ORD-2024-0847
MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTL
VTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVN
RIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHY
QQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK`,
  },
  {
    name: "SYN-00142",
    description: "Protein sequence, 535 aa — 2 domains detected",
    hasMockReport: true,
    sequence: `>SYN-00142
IFPKQYPIINFTTAGATVQSYTNFIRAVRGRLTTGADVRHEIPVLPNRVGLPINQRFILY
ELSNHSAELSVTLALDVTNAYVVGYRAGNSAYFFHPDNQEDAEAITHLFTDVQNRYTFAF
GGNYDRLEQLAGNLRENIELGNGPLEEAISALYYYSTGGTQLPTLARSFIICIQMISEAAR
FQYIEGEMRTRIRYNRRSAPDPSVITLENSWGRLSTAIQESNQGAFASPIQLQRRNGSKFP
VKDHLDKLEAQIGTCVSF`,
  },
  {
    name: "ORD-2024-1533",
    description: "Protein sequence, 267 aa — 2 domains detected",
    hasMockReport: true,
    sequence: `>ORD-2024-1533
MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPE
ERFPMMSTFKVLLCGAVLSRIDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELS
CSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMP
VAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRG
IIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW`,
  },
];
