export interface ExampleSequence {
  name: string;
  description: string;
  expectedRisk: "LOW" | "MEDIUM" | "HIGH" | "UNKNOWN";
  sequence: string;
}

export const exampleSequences: ExampleSequence[] = [
  {
    name: "GFP (Green Fluorescent Protein)",
    description: "Aequorea victoria GFP — common lab reporter protein",
    expectedRisk: "LOW",
    sequence: `>GFP_Aequorea_victoria
MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTL
VTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVN
RIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHY
QQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK`,
  },
  {
    name: "Ricin A-chain",
    description: "Ricinus communis ricin toxin A-chain — known select agent toxin",
    expectedRisk: "HIGH",
    sequence: `>Ricin_A_chain_Ricinus_communis
IFPKQYPIINFTTAGATVQSYTNFIRAVRGRLTTGADVRHEIPVLPNRVGLPINQRFILY
ELSNHSAELSVTLALDVTNAYVVGYRAGNSAYFFHPDNQEDAEAITHLFTDVQNRYTFAF
GGNYDRLEQLAGNLRENIELGNGPLEEAISALYYYSTGGTQLPTLARSFIICIQMISEAAR
FQYIEGEMRTRIRYNRRSAPDPSVITLENSWGRLSTAIQESNQGAFASPIQLQRRNGSKFP
VKDHLDKLEAQIGTCVSF`,
  },
  {
    name: "ampR (Beta-lactamase)",
    description: "TEM-1 beta-lactamase — confers ampicillin resistance",
    expectedRisk: "MEDIUM",
    sequence: `>TEM1_beta_lactamase
MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPE
ERFPMMSTFKVLLCGAVLSRIDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELS
CSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMP
VAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRG
IIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW`,
  },
  {
    name: "Unknown Fragment",
    description: "Short unidentified nucleotide fragment",
    expectedRisk: "UNKNOWN",
    sequence: `>Unknown_fragment
ATGCGTACCTGAACGGTTACGATCGATTACGCTAGCTACGATCGATCGATCGTAGCTAGCT
ACGATCGATCGATCGTAGCTAGCTACGATCGATCG`,
  },
];
