export interface ExampleSequence {
  name: string;
  description: string;
  sequence: string;
}

export const exampleSequences: ExampleSequence[] = [
  {
    name: "ORD-2024-0847",
    description: "Customer synthesis order — protein sequence, 238 aa",
    sequence: `>ORD-2024-0847
MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTL
VTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVN
RIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHY
QQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK`,
  },
  {
    name: "SYN-00142",
    description: "Customer synthesis order — protein sequence, 267 aa",
    sequence: `>SYN-00142
IFPKQYPIINFTTAGATVQSYTNFIRAVRGRLTTGADVRHEIPVLPNRVGLPINQRFILY
ELSNHSAELSVTLALDVTNAYVVGYRAGNSAYFFHPDNQEDAEAITHLFTDVQNRYTFAF
GGNYDRLEQLAGNLRENIELGNGPLEEAISALYYYSTGGTQLPTLARSFIICIQMISEAAR
FQYIEGEMRTRIRYNRRSAPDPSVITLENSWGRLSTAIQESNQGAFASPIQLQRRNGSKFP
VKDHLDKLEAQIGTCVSF`,
  },
  {
    name: "ORD-2024-1533",
    description: "Customer synthesis order — protein sequence, 286 aa",
    sequence: `>ORD-2024-1533
MSIQHFRVALIPFFAAFCLPVFAHPETLVKVKDAEDQLGARVGYIELDLNSGKILESFRPE
ERFPMMSTFKVLLCGAVLSRIDAGQEQLGRRIHYSQNDLVEYSPVTEKHLTDGMTVRELS
CSAAITMSDNTAANLLLTTIGGPKELTAFLHNMGDHVTRLDRWEPELNEAIPNDERDTTMP
VAMATTLRKLLTGELLTLASRQQLIDWMEADKVAGPLLRSALPAGWFIADKSGAGERGSRG
IIAALGPDGKPSRIVVIYTTGSQATMDERNRQIAEIGASLIKHW`,
  },
  {
    name: "SYN-00391",
    description: "Customer synthesis order — nucleotide fragment, 95 bp",
    sequence: `>SYN-00391
ATGCGTACCTGAACGGTTACGATCGATTACGCTAGCTACGATCGATCGATCGTAGCTAGCT
ACGATCGATCGATCGTAGCTAGCTACGATCGATCG`,
  },
];
